name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/google.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean and Clone git
        run: |
          rm -rf *
          git clone https://github.com/liorfizz/ci-cd.git

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Cleanup Container
        run: |
          pip install docker
          echo "apply the script"
          cd ci-cd/alpacaflask
          python3 pythonversioning.py

  deploy-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true

      - name: Package Helm and Upload
        run: |
          cd /my-chart
          chmod +x Helm-version.sh
          ./Helm-version.sh

      - name: Deploy Test Gcloud
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials test-cluster --region=europe-central2
          helm repo add my-chart-repo https://storage.googleapis.com/helmflask-bucket/
          helm repo update
          helm upgrade --install alpaca my-chart-repo/my-chart

      - name: Get External IP
        run: |
          kubectl get svc flask-app-service --no-headers | awk '{print $4}' > external_ip_qa.txt
          externalIP=$(cat 'external_ip_qa.txt')

          while [ "$externalIP" = "<pending>" ]; do
              rm external_ip_qa.txt
              sleep 30
              kubectl get svc flask-app-service --no-headers | awk '{print $4}' > external_ip_qa.txt
              externalIP=$(cat 'external_ip_qa.txt')
          done

          echo "...finishing deploy..."

      - name: Q/A Connection
        run: |
          externalIP=$(cat 'external_ip_qa.txt')
          curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${externalIP}:5000)
          if [ "$curl_output" -eq "200" ]; then
              echo "Site is working (200 OK)"
          else
              echo "Error: Site is not working"
              exit 1
          fi

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Prod Gcloud
        run: |
          gcloud container clusters get-credentials flask-cluster --region=europe-central2
          helm repo add my-chart-repo https://storage.googleapis.com/helmflask-bucket/
          helm repo update
          helm upgrade --install alpaca my-chart-repo/my-chart
